/* tools/embed.c - turn a web asset into a C byte array.
 *
 *   embed <input-file> <output-header> <symbol>
 *
 * Emitting raw bytes rather than an escaped string keeps the generated header
 * immune to charset and escape-sequence surprises: what the browser gets is
 * exactly the bytes that are in web/*.html. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv)
{
    FILE *in, *out;
    unsigned char *buf;
    long size;
    long i;
    char guard[128];

    if (argc != 4) {
        fprintf(stderr, "usage: embed <input> <output.h> <symbol>\n");
        return 2;
    }

    in = fopen(argv[1], "rb");
    if (!in) { fprintf(stderr, "embed: cannot open %s\n", argv[1]); return 1; }
    fseek(in, 0, SEEK_END);
    size = ftell(in);
    fseek(in, 0, SEEK_SET);
    if (size < 0) { fclose(in); return 1; }

    buf = (unsigned char *)malloc((size_t)size + 1);
    if (!buf) { fclose(in); return 1; }
    if (size > 0 && fread(buf, 1, (size_t)size, in) != (size_t)size) {
        fprintf(stderr, "embed: short read on %s\n", argv[1]);
        fclose(in); free(buf); return 1;
    }
    fclose(in);

    _snprintf(guard, sizeof(guard), "PW_EMBEDDED_%s_H", argv[3]);
    for (i = 0; guard[i]; i++) {
        if (guard[i] >= 'a' && guard[i] <= 'z') guard[i] = (char)(guard[i] - 'a' + 'A');
        if (!((guard[i] >= 'A' && guard[i] <= 'Z') || (guard[i] >= '0' && guard[i] <= '9') ||
              guard[i] == '_'))
            guard[i] = '_';
    }

    out = fopen(argv[2], "wb");
    if (!out) { fprintf(stderr, "embed: cannot write %s\n", argv[2]); free(buf); return 1; }

    fprintf(out, "/* Generated by tools/embed.c from %s - do not edit. */\n", argv[1]);
    fprintf(out, "#ifndef %s\n#define %s\n\n", guard, guard);
    fprintf(out, "const unsigned char %s[] = {\n", argv[3]);
    for (i = 0; i < size; i++) {
        if (i % 16 == 0) fprintf(out, "    ");
        fprintf(out, "0x%02X,", buf[i]);
        if (i % 16 == 15 || i == size - 1) fprintf(out, "\n");
        else fprintf(out, " ");
    }
    if (size == 0) fprintf(out, "    0x00\n");
    fprintf(out, "};\n");
    fprintf(out, "const unsigned int %s_len = %ld;\n\n", argv[3], size);
    fprintf(out, "#endif /* %s */\n", guard);
    fclose(out);
    free(buf);
    return 0;
}
